---
name: Docker build

on:
    - push

jobs:
    docker:
        runs-on: ubuntu-latest
        name: build and test
        steps:
            - uses: actions/checkout@v1
            - name: docker build
              run: docker build . --build-arg CPM_ARGS='--with-test' -t api
            - name: up
              run: docker-compose up -d api
            - name: run Perl tests
              run: docker-compose exec api prove -lvr t
